# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_rst_clk_wiz_1_100M_0/WiFi_rst_clk_wiz_1_100M_0.xci
# IP: The module: 'WiFi_rst_clk_wiz_1_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_rst_clk_wiz_1_100M_0/WiFi_rst_clk_wiz_1_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'WiFi_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_rst_clk_wiz_1_100M_0/WiFi_rst_clk_wiz_1_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'WiFi_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_rst_clk_wiz_1_100M_0/WiFi_rst_clk_wiz_1_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'WiFi_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_rst_clk_wiz_1_100M_0/WiFi_rst_clk_wiz_1_100M_0.xci
# IP: The module: 'WiFi_rst_clk_wiz_1_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_rst_clk_wiz_1_100M_0/WiFi_rst_clk_wiz_1_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'WiFi_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_rst_clk_wiz_1_100M_0/WiFi_rst_clk_wiz_1_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'WiFi_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_rst_clk_wiz_1_100M_0/WiFi_rst_clk_wiz_1_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'WiFi_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
