# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/WiFi.xdc

# Block Designs: bd/WiFi/WiFi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi || ORIG_REF_NAME==WiFi}]

# IP: bd/WiFi/ip/WiFi_microblaze_0_0/WiFi_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_microblaze_0_0 || ORIG_REF_NAME==WiFi_microblaze_0_0}]

# IP: bd/WiFi/ip/WiFi_dlmb_v10_0/WiFi_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_dlmb_v10_0 || ORIG_REF_NAME==WiFi_dlmb_v10_0}]

# IP: bd/WiFi/ip/WiFi_ilmb_v10_0/WiFi_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_ilmb_v10_0 || ORIG_REF_NAME==WiFi_ilmb_v10_0}]

# IP: bd/WiFi/ip/WiFi_dlmb_bram_if_cntlr_0/WiFi_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==WiFi_dlmb_bram_if_cntlr_0}]

# IP: bd/WiFi/ip/WiFi_ilmb_bram_if_cntlr_0/WiFi_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==WiFi_ilmb_bram_if_cntlr_0}]

# IP: bd/WiFi/ip/WiFi_lmb_bram_0/WiFi_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_lmb_bram_0 || ORIG_REF_NAME==WiFi_lmb_bram_0}]

# IP: bd/WiFi/ip/WiFi_microblaze_0_axi_periph_0/WiFi_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_microblaze_0_axi_periph_0 || ORIG_REF_NAME==WiFi_microblaze_0_axi_periph_0}]

# IP: bd/WiFi/ip/WiFi_microblaze_0_axi_intc_0/WiFi_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_microblaze_0_axi_intc_0 || ORIG_REF_NAME==WiFi_microblaze_0_axi_intc_0}]

# IP: bd/WiFi/ip/WiFi_microblaze_0_xlconcat_0/WiFi_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_microblaze_0_xlconcat_0 || ORIG_REF_NAME==WiFi_microblaze_0_xlconcat_0}]

# IP: bd/WiFi/ip/WiFi_mdm_1_0/WiFi_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_mdm_1_0 || ORIG_REF_NAME==WiFi_mdm_1_0}]

# IP: bd/WiFi/ip/WiFi_clk_wiz_1_0/WiFi_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_clk_wiz_1_0 || ORIG_REF_NAME==WiFi_clk_wiz_1_0}]

# IP: bd/WiFi/ip/WiFi_rst_clk_wiz_1_100M_0/WiFi_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==WiFi_rst_clk_wiz_1_100M_0}]

# IP: bd/WiFi/ip/WiFi_axi_emc_0_0/WiFi_axi_emc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_axi_emc_0_0 || ORIG_REF_NAME==WiFi_axi_emc_0_0}]

# IP: bd/WiFi/ip/WiFi_axi_uartlite_0_0/WiFi_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_axi_uartlite_0_0 || ORIG_REF_NAME==WiFi_axi_uartlite_0_0}]

# IP: bd/WiFi/ip/WiFi_mii_to_rmii_0_0/WiFi_mii_to_rmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_mii_to_rmii_0_0 || ORIG_REF_NAME==WiFi_mii_to_rmii_0_0}]

# IP: bd/WiFi/ip/WiFi_axi_ethernetlite_0_0/WiFi_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_axi_ethernetlite_0_0 || ORIG_REF_NAME==WiFi_axi_ethernetlite_0_0}]

# IP: bd/WiFi/ip/WiFi_axi_timer_0_0/WiFi_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_axi_timer_0_0 || ORIG_REF_NAME==WiFi_axi_timer_0_0}]

# IP: bd/WiFi/ip/WiFi_axi_quad_spi_0_0/WiFi_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_axi_quad_spi_0_0 || ORIG_REF_NAME==WiFi_axi_quad_spi_0_0}]

# IP: bd/WiFi/ip/WiFi_axi_mem_intercon_0/WiFi_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_axi_mem_intercon_0 || ORIG_REF_NAME==WiFi_axi_mem_intercon_0}]

# IP: bd/WiFi/ip/WiFi_xbar_0/WiFi_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_xbar_0 || ORIG_REF_NAME==WiFi_xbar_0}]

# IP: bd/WiFi/ip/WiFi_xbar_1/WiFi_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WiFi_xbar_1 || ORIG_REF_NAME==WiFi_xbar_1}]

# XDC: bd/WiFi/WiFi_ooc.xdc
