# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.cache/wt [current_project]
set_property parent.project_path C:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
set_property ip_output_repo c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/hdl/WiFi_wrapper.v
add_files C:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/WiFi.bd
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_microblaze_0_0/WiFi_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_microblaze_0_0/WiFi_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_microblaze_0_0/WiFi_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_dlmb_v10_0/WiFi_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_dlmb_v10_0/WiFi_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_ilmb_v10_0/WiFi_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_ilmb_v10_0/WiFi_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_dlmb_bram_if_cntlr_0/WiFi_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_ilmb_bram_if_cntlr_0/WiFi_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_lmb_bram_0/WiFi_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_microblaze_0_axi_intc_0/WiFi_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_microblaze_0_axi_intc_0/WiFi_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_microblaze_0_axi_intc_0/WiFi_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_mdm_1_0/WiFi_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_mdm_1_0/WiFi_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_clk_wiz_1_0/WiFi_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_clk_wiz_1_0/WiFi_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_clk_wiz_1_0/WiFi_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_rst_clk_wiz_1_100M_0/WiFi_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_rst_clk_wiz_1_100M_0/WiFi_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_rst_clk_wiz_1_100M_0/WiFi_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_emc_0_0/WiFi_axi_emc_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_emc_0_0/WiFi_axi_emc_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_emc_0_0/WiFi_axi_emc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_uartlite_0_0/WiFi_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_uartlite_0_0/WiFi_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_uartlite_0_0/WiFi_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_mii_to_rmii_0_0/WiFi_mii_to_rmii_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_mii_to_rmii_0_0/WiFi_mii_to_rmii_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_ethernetlite_0_0/WiFi_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_ethernetlite_0_0/WiFi_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_ethernetlite_0_0/WiFi_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_ethernetlite_0_0/WiFi_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_timer_0_0/WiFi_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_timer_0_0/WiFi_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_quad_spi_0_0/WiFi_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_quad_spi_0_0/WiFi_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_quad_spi_0_0/WiFi_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_axi_quad_spi_0_0/WiFi_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_xbar_0/WiFi_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/ip/WiFi_xbar_1/WiFi_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/WiFi_ooc.xdc]
set_property is_locked true [get_files C:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/sources_1/bd/WiFi/WiFi.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/constrs_1/new/WiFi.xdc
set_property used_in_implementation false [get_files C:/College/Thesis/VivadoProjects/WiFi/WiFi/WiFi.srcs/constrs_1/new/WiFi.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top WiFi_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef WiFi_wrapper.dcp

catch { report_utilization -file WiFi_wrapper_utilization_synth.rpt -pb WiFi_wrapper_utilization_synth.pb }
